apiVersion: apps/v1
kind: Deployment

metadata:
  name: python-app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-frontend
      
  template:
    metadata:
      labels:
        app: app-frontend
    spec:
      containers:
        - name: python-app
          image: to add after creting image on GCR
          ports:
            - containerPort: 8080
          env:
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: app
                key: ENVIRONMENT
                
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: app
                key: HOST
                
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: app
                key: PORT
                
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: app
                key: REDIS_HOST
              
          - name: REDIS_PORT
            valueFrom:
              configMapKeyRef:
                name: app
                key: REDIS_PORT
                
           - name: REDIS_DB
            valueFrom:
              configMapKeyRef:
                name: app
                key: REDIS_DB
                
          
